---
include:
  - remote: 'https://gitlab.com/op_so/projects/gitlab-ci-templates/-/raw/main/templates/gitlab-release.gitlab-ci.yml'

variables:
  IMAGE_DEFAULT: alpine:latest
  IMAGE_DOCKER: docker:latest
  IMAGE_LYCHEE: lycheeverse/lychee:latest
  IMAGE_MARKDOWNLINT: davidanson/markdownlint-cli2
  IMAGE_NODE: node:lts-bullseye
  IMAGE_SHELLCHECK: koalaman/shellcheck:stable
  IMAGE_YAMLLINT: jfxs/ansible
  SERVICE_DOCKER_TAG: stable-dind

stages:
  - lint
  - tests
  - gitlab-release

lint-file:
  image: $IMAGE_DEFAULT
  stage: lint
  before_script:
    - apk --no-cache add curl file git ncurses
    - sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
    - task --version
  script:
    - task lint:file

lint-lychee:
  image:
    name: $IMAGE_LYCHEE
    entrypoint: [""]
  stage: lint
  before_script:
    - sh -c "$(wget -qO - https://taskfile.dev/install.sh)" -- -d
    - ./bin/task --version
  script:
    - ./bin/task lint:lychee
  allow_failure: true

lint-markdown:
  image:
    name: $IMAGE_MARKDOWNLINT
    entrypoint: [""]
  stage: lint
  before_script:
    - sh -c "$(wget -qO - https://taskfile.dev/install.sh)" -- -d
    - ./bin/task --version
  script:
    - ./bin/task lint:markdown G="\"**/*.md\" \"#node_modules\" \"#.node_cache\""

lint-yaml:
  image:
    name: $IMAGE_YAMLLINT
  stage: lint
  before_script:
    - sh -c "$(wget -qO - https://taskfile.dev/install.sh)" -- -d
    - ./bin/task --version
  script:
    - ./bin/task lint:yaml

lint-docker-dind:
  image:
    name: $IMAGE_DOCKER
  services:
    - docker:$SERVICE_DOCKER_TAG
  stage: tests
  before_script:
    - sh -c "$(wget -qO - https://taskfile.dev/install.sh)" -- -d
    - ./bin/task --version
  script:
    - ./bin/task lint:docker FILE="tests/lint/Dockerfile"

lint-lychee-dind:
  extends: lint-docker-dind
  script:
    - ./bin/task lint:lychee
  allow_failure: true

lint-markdown-dind:
  extends: lint-docker-dind
  script:
    - ./bin/task lint:markdown

lint-shell-dind:
  extends: lint-docker-dind
  script:
    - ./bin/task lint:shell FILES="tests/lint/*.sh"

lint-yaml-dind:
  extends: lint-docker-dind
  script:
    - ./bin/task lint:yaml
