---
workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always

variables:
  IMAGE_DEFAULT: alpine:latest
  IMAGE_DOCKER: docker:latest
  IMAGE_MARKDOWNLINT: davidanson/markdownlint-cli2
  IMAGE_NODE: node:lts-bullseye
  IMAGE_SHELLCHECK: koalaman/shellcheck:stable
  IMAGE_YAMLLINT: jfxs/ansible
  SERVICE_DOCKER_TAG: stable-dind

stages:
  - checks
  - tests
  - gitlab-release

lint-file:
  image: $IMAGE_DEFAULT
  stage: checks
  before_script:
    - apk --no-cache add curl file git ncurses
    - sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
    - task --version
  script:
    - task lint:file

lint-markdown:
  image:
    name: $IMAGE_MARKDOWNLINT
    entrypoint: [""]
  stage: checks
  before_script:
    - sh -c "$(wget -qO - https://taskfile.dev/install.sh)" -- -d
    - ./bin/task --version
  script:
    - ./bin/task lint:markdown G="\"**/*.md\" \"#node_modules\" \"#.node_cache\""

lint-yaml:
  image:
    name: $IMAGE_YAMLLINT
  stage: checks
  before_script:
    - sh -c "$(wget -qO - https://taskfile.dev/install.sh)" -- -d
    - ./bin/task --version
  script:
    - ./bin/task lint:yaml

lint-markdown-dind:
  image:
    name: $IMAGE_DOCKER
  services:
    - docker:$SERVICE_DOCKER_TAG
  stage: tests
  before_script:
    - sh -c "$(wget -qO - https://taskfile.dev/install.sh)" -- -d
    - ./bin/task --version
  script:
    - ./bin/task lint:markdown

lint-shell-dind:
  image:
    name: $IMAGE_DOCKER
  services:
    - docker:$SERVICE_DOCKER_TAG
  stage: tests
  before_script:
    - sh -c "$(wget -qO - https://taskfile.dev/install.sh)" -- -d
    - ./bin/task --version
  script:
    - ./bin/task lint:shell FILES="tests/lint/*.sh"

lint-yaml-dind:
  image:
    name: $IMAGE_DOCKER
  services:
    - docker:$SERVICE_DOCKER_TAG
  stage: tests
  before_script:
    - sh -c "$(wget -qO - https://taskfile.dev/install.sh)" -- -d
    - ./bin/task --version
  script:
    - ./bin/task lint:yaml

gitlab-release:
  only:
    refs:
      - main
  image: $IMAGE_NODE
  stage: gitlab-release
  before_script:
    - yarn install
  script:
    - npx semantic-release
