---
include:
  - remote: 'https://gitlab.com/op_so/projects/gitlab-ci-templates/-/raw/main/templates/lint.gitlab-ci.yml'
  - remote: 'https://gitlab.com/op_so/projects/gitlab-ci-templates/-/raw/main/templates/gitlab-release.gitlab-ci.yml'

variables:
  IMAGE_DEFAULT: alpine:latest
  # IMAGE_DOCKER: docker:latest
  IMAGE_DOCKER: docker:25
  IMAGE_LYCHEE: lycheeverse/lychee:latest
  IMAGE_MARKDOWNLINT: davidanson/markdownlint-cli2
  IMAGE_NODE: node:lts-bookworm
  IMAGE_PRECOMMIT: jfxs/pre-commit
  IMAGE_SHELLCHECK: koalaman/shellcheck:stable
  IMAGE_YAMLLINT: jfxs/ansible
  LINT_VALE: "true"
  # SERVICE_DOCKER_TAG: stable-dind
  SERVICE_DOCKER_TAG: 25-dind

stages:
  - lint
  - tests
  - gitlab-release

lint-docker-dind:
  image:
    name: $IMAGE_DOCKER
  services:
    - docker:$SERVICE_DOCKER_TAG
  stage: tests
  before_script:
    - sh -c "$(wget -qO - https://taskfile.dev/install.sh)" -- -d
    - ./bin/task --version
  script:
    - ./bin/task lint:docker FILE="tests/lint/Dockerfile"

lint-lychee-dind:
  extends: lint-docker-dind
  script:
    - ./bin/task lint:lychee
  allow_failure: true

lint-markdown-dind:
  extends: lint-docker-dind
  script:
    - ./bin/task lint:markdown

lint-shell-dind:
  extends: lint-docker-dind
  script:
    - ./bin/task lint:shell FILES="tests/lint/*.sh"

lint-vale-dind:
  extends: lint-docker-dind
  script:
    - ./bin/task lint:vale

lint-yaml-dind:
  extends: lint-docker-dind
  script:
    - ./bin/task lint:yaml
