---
workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always

variables:
  IMAGE_DEFAULT: alpine:latest
  IMAGE_NODE: node:lts-bullseye
  IMAGE_YAMLLINT: cytopia/yamllint

stages:
  - checks
  - gitlab-release

lint-yaml:
  image:
    name: $IMAGE_YAMLLINT
    entrypoint: ["/bin/ash", "-c"]
  stage: checks
  script:
    - yamllint -f colored .

lint-file:
  image: $IMAGE_DEFAULT
  stage: checks
  before_script:
    - apk --no-cache add curl file git ncurses
    - sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
    - task --version
  script:
    - task lint:file

gitlab-release:
  only:
    refs:
      - main
  image: $IMAGE_NODE
  stage: gitlab-release
  before_script:
    - yarn install
  script:
    - npx semantic-release
