---
# https://taskfile.dev

version: '3'

vars:
  DIR_TASKFILES: "Taskfile.d"
  FILE_TASK_START: "task-start-{{.TASK}}.tmp"
  MAT_GIT_REPO: "https://gitlab.com/jfxs-multipass/multipass-ansible-toolkit/-/raw/main"

includes:
  00:
    taskfile: "./Taskfile.project.yml"
  git:
    taskfile: "./Taskfile.d/git.yml"
  lint:
    taskfile: "./Taskfile.d/lint.yml"
  multipass:
    taskfile: "./Taskfile.d/multipass.yml"
  yarn:
    taskfile: "./Taskfile.d/yarn.yml"

tasks:

  usage:
    desc: "[CORE] Show the usage of a task. Arguments: TSK|T=task-name [FILE|F=Taskfile.dist.yml] (*)"
    summary: |
      [CORE] Show the usage of a task.
      Usage: task [-t Taskfile.dist.yml] usage TSK|T=<task-name> [FILE|F=Taskfile.dist.yml]

      Arguments:
       TSK | T  Name of the task (required)
       FILE | F Taskfile path (optional, by default Taskfile.yml)
    vars:
      TSK: '{{default .T .TSK}}'
      FILE: '{{default .F .FILE}}'
      FILE_DEFAULT: "Taskfile.yml"
      FILE_PATH: '{{default .FILE_DEFAULT .FILE}}'
    cmds:
      - |
        if [ ! -f "{{.FILE_PATH}}" ]; then
          echo "{{.FILE_PATH}} does not exist!"
          exit 1
        fi
      - task -t "{{.FILE_PATH}}" --summary "{{.TSK}}" | sed '/^dependencies:$/,$d' | sed '/^commands:$/,$d'
    preconditions:
      - sh: test -n "{{.TSK}}" || test -n "{{.T}}"
        msg: "TSK|T argument is required"
    silent: true

  default:
    desc: "[CORE] List of available tasks. Arguments: [FILE|F=Taskfile.dist.yml] (*)"
    summary: |
      [CORE] Show the list of available tasks.
      Usage: task [-t Taskfile.dist.yml] [FILE|F=Taskfile.dist.yml]

      Arguments:
       FILE | F Taskfile path (optional, by default Taskfile.yml)
    vars:
      FILE: '{{default .F .FILE}}'
      FILE_DEFAULT: "Taskfile.yml"
      FILE_PATH: '{{default .FILE_DEFAULT .FILE}}'
      TASKS_LIST:
        sh: task -t "{{.FILE_PATH}}" --list
    cmds:
      - |
        {{ range $i, $line := .TASKS_LIST | splitLines -}}
          first_char="$(printf '%s' "{{ $line }}" | cut -c1)"
          if [ "$first_char" = "*" ]; then
             task=$(echo "{{ $line }}" | cut -d ' ' -f2)
             desc=$(echo "{{ $line }}" | sed -e "s/^\* $task//" | sed 's/^[[:space:]]*//g')
             printf "\e[32m%-25s \033[0m %s\n" "* $task" "$desc"
          else
            echo "{{ $line }}"
          fi
        {{ end -}}
      - echo ""
      - echo " (*) task usage TSK=<task-name> will show the usage of the task."
      - echo ""
    silent: true
